fix init.d script

diff --git a/templates/etc/init.d/syncthing.j2 b/templates/etc/init.d/syncthing.j2
--- a/templates/etc/init.d/syncthing.j2
+++ b/templates/etc/init.d/syncthing.j2
@@ -1,79 +1,86 @@
 #!/bin/sh
+### BEGIN INIT INFO
+# Provides:          syncthing_{{role_syncthing_user}}
+# Required-Start:    $local_fs $network $named $time $syslog
+# Required-Stop:     $local_fs $network $named $time $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Description:       syncthing
+### END INIT INFO
 
-USER={{role_syncthing_user}}
-SERVICE_NAME=syncthing_{{role_syncthing_user}}
-DAEMON="su"
-DAEMON_OPTS="-l {{role_syncthing_user}} {{syncthing_path}}/syncthing -no-browser -logflags=0"
-PIDFILE=/var/run/syncthing_{{role_syncthing_user}}.pid
+SCRIPT="{{syncthing_path}}/syncthing -no-browser -logflags=0"
+RUNAS="{{role_syncthing_user}}"
+NAME="syncthing_{{role_syncthing_user}}"
 
-if [ ! -x $DAEMON ]; then
-  echo "ERROR: Can't execute $DAEMON."
-  exit 1
-fi
+PIDFILE=/var/run/$NAME.pid
+LOGFILE=/var/log/$NAME.log
 
-start_service() {
-  echo -n " * Starting $SERVICE_NAME... "
-  start-stop-daemon -Sq -p $PIDFILE -x $DAEMON -- $DAEMON_OPTS
-  e=$?
-  if [ $e -eq 1 ]; then
-    echo "already running"
-    return
+start() {
+  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
+    echo 'Service already running' >&2
+    return 1
   fi
-
-  if [ $e -eq 255 ]; then
-    echo "couldn't start :("
-    exit 1
-  fi
-
-  echo "done"
+  echo 'Starting service…' >&2
+  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
+  su -c "$CMD" $RUNAS > "$PIDFILE"
+  echo 'Service started' >&2
 }
 
-stop_service() {
-  echo -n " * Stopping $SERVICE_NAME... "
-  start-stop-daemon -Kq -R 10 -p $PIDFILE
-  e=$?
-  if [ $e -eq 1 ]; then
-    echo "not running"
-    return
+stop() {
+  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
+    echo 'Service not running' >&2
+    return 1
   fi
-
-  echo "done"
+  echo 'Stopping service…' >&2
+  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
+  echo 'Service stopped' >&2
 }
 
-status_service() {
-    printf "%-50s" "Checking $SERVICE_NAME..."
+uninstall() {
+  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
+  local SURE
+  read SURE
+  if [ "$SURE" = "yes" ]; then
+    stop
+    rm -f "$PIDFILE"
+    echo "Notice: log file was not removed: '$LOGFILE'" >&2
+    update-rc.d -f <NAME> remove
+    rm -fv "$0"
+  fi
+}
+
+status() {
+        printf "%-50s" "Checking $NAME..."
     if [ -f $PIDFILE ]; then
-        PID=`cat $PIDFILE`
-        if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
-            printf "%s\n" "Process dead but pidfile exists"
-            exit 1 
-        else
-            echo "Running"
-        fi
+        PID=$(cat $PIDFILE)
+            if [ -z "$(ps axf | grep ${PID} | grep -v grep)" ]; then
+                printf "%s\n" "The process appears to be dead but pidfile still exists"
+            else    
+                echo "Running, the PID is $PID"
+            fi
     else
         printf "%s\n" "Service not running"
-        exit 3 
     fi
 }
 
+
 case "$1" in
-  status)
-    status_service
-    ;;
   start)
-    start_service
+    start
     ;;
   stop)
-    stop_service
+    stop
+    ;;
+  status)
+    status
+    ;;
+  uninstall)
+    uninstall
     ;;
   restart)
-    stop_service
-    start_service
+    stop
+    start
     ;;
   *)
-    echo "Usage: service $SERVICE_NAME {start|stop|restart|status}" >&2
-    exit 1   
-    ;;
+    echo "Usage: $0 {start|stop|status|restart|uninstall}"
 esac
-
-exit 0
